name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        include: 
        - os: ubuntu-18.04
          TARGET: x86_64-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc

        - os: ubuntu-16.04
          TARGET: x86_64-unknown-linux-musl
          COMPILER: gcc
          LINKER: gcc
    steps:
     - uses: actions/checkout@v1
     - name: installAndTest 16
       if: runner.os == 'ubuntu-16.04'
       run: |
          sudo apt-get update	
          cd solution && mkdir -p generated && ls -l */*.js | awk '{print $9}' | awk  -F  "/"  '{print $0,$1,$2}' | while read full dir file ; do cp "$full" generated/"$dir"_"$file"; done
          diff -q generated/ ../expectedNodeOCCJSScripts/
     - name: installAndTest 18
       if: runner.os == 'ubuntu-18.04'
       run: |
          sudo apt-get update	
          cd solution && mkdir -p generated &&  ls -l */*.js | awk '{print $9}' | awk  -F  "/"  '{print $0,$1,$2}' | while read full dir file ; do cp "$full" generated/"$dir"_"$file"; done
          diff -q generated/ ../expectedNodeOCCJSScripts/